export const GET_GOODS__REQUEST = 'GET_GOODS__REQUEST';
export const GET_GOODS__SUCCESS = 'GET_GOODS__SUCCESS';
export const GET_GOODS__FAILURE = 'GET_GOODS__FAILURE';

export const CHANGE_QUANTITY = 'CHANGE_QUANTITY';
export const DELETE_GOOD = 'DELETE_GOOD';